name: udacity_rentals
channels:
  - conda-forge
dependencies:
  - python = 3.8
  - black == 20.8b1
  - pip >= 19.0.*
  - pandas == 1.1.*
  - pre_commit == 2.9.3
  - shap == 0.39.0
  - scikit-learn == 0.24.2
  - pylint
  - autopep8
  - seaborn == 0.11.2
  - lightgbm = 3.2.1
  - mlflow
  - requests
  - pip:
      - wandb
      - sphinx == 3.2.0
      - sphinx-rtd-theme == 0.4.3
      - pytest == 4.3.1
      - python-box == 5.1.1
